#!/bin/bash

# Check if at least 4 parameters are provided
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
file_to_transfer="$1"
remote_host="$2"
remote_user="$3"
ssh_key="$4"

# Use SCP to transfer the file to the remote server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_to_transfer" "$remote_user@$remote_host:~/"

# Check if SCP was successful
if [ "$?" -eq 0 ]; then
  echo "File transferred successfully."
else
  echo "File transfer failed."
fi

